config/routes.rb
Sonetto::Application.routes.draw do
  resources :perfis

  devise_for :users

end

app/models/perfil.rb
class Perfil < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :perfil         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/perfis_controller.rb
class PerfisController < ApplicationController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfis
  # GET /perfis.json
  def index
    @perfis = Perfil.all
  end

  # GET /perfis/1
  # GET /perfis/1.json
  def show
  end

  # GET /perfis/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfis/1/edit
  def edit
  end

  # POST /perfis
  # POST /perfis.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil was successfully created.' }
        format.json { render action: 'show', status: :created, location: @perfil }
      else
        format.html { render action: 'new' }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfis/1
  # PATCH/PUT /perfis/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfis/1
  # DELETE /perfis/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:nome_da_empresa, :razao_social, :cnpj, :telefone, :nome_do_responsavel, :telefone_do_responsavel, :email_do_responsavel, :rua, :numero, :cep, :bairro, :cidade, :estado, :complemento, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfis_helper.rb
module PerfisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sonetto</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/perfis/_form.html.erb
<%= simple_form_for(@perfil) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome_da_empresa %>
    <%= f.input :razao_social %>
    <%= f.input :cnpj %>
    <%= f.input :telefone %>
    <%= f.input :nome_do_responsavel %>
    <%= f.input :telefone_do_responsavel %>
    <%= f.input :email_do_responsavel %>
    <%= f.input :rua %>
    <%= f.input :numero %>
    <%= f.input :cep %>
    <%= f.input :bairro %>
    <%= f.input :cidade %>
    <%= f.input :estado %>
    <%= f.input :complemento %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/perfis/edit.html.erb
<h1>Editing perfil</h1>

<%= render 'form' %>

<%= link_to 'Show', @perfil %> |
<%= link_to 'Back', perfis_path %>

app/views/perfis/index.html.erb
<h1>Listing perfis</h1>

<table>
  <thead>
    <tr>
      <th>Nome da empresa</th>
      <th>Razao social</th>
      <th>Cnpj</th>
      <th>Telefone</th>
      <th>Nome do responsavel</th>
      <th>Telefone do responsavel</th>
      <th>Email do responsavel</th>
      <th>Rua</th>
      <th>Numero</th>
      <th>Cep</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Complemento</th>
      <th>Usuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @perfis.each do |perfil| %>
      <tr>
        <td><%= perfil.nome_da_empresa %></td>
        <td><%= perfil.razao_social %></td>
        <td><%= perfil.cnpj %></td>
        <td><%= perfil.telefone %></td>
        <td><%= perfil.nome_do_responsavel %></td>
        <td><%= perfil.telefone_do_responsavel %></td>
        <td><%= perfil.email_do_responsavel %></td>
        <td><%= perfil.rua %></td>
        <td><%= perfil.numero %></td>
        <td><%= perfil.cep %></td>
        <td><%= perfil.bairro %></td>
        <td><%= perfil.cidade %></td>
        <td><%= perfil.estado %></td>
        <td><%= perfil.complemento %></td>
        <td><%= perfil.user_id %></td>
        <td><%= link_to 'Show', perfil %></td>
        <td><%= link_to 'Edit', edit_perfil_path(perfil) %></td>
        <td><%= link_to 'Destroy', perfil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perfil', new_perfil_path %>

app/views/perfis/new.html.erb
<h1>New perfil</h1>

<%= render 'form' %>

<%= link_to 'Back', perfis_path %>

app/views/perfis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome da empresa:</strong>
  <%= @perfil.nome_da_empresa %>
</p>

<p>
  <strong>Razao social:</strong>
  <%= @perfil.razao_social %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @perfil.cnpj %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @perfil.telefone %>
</p>

<p>
  <strong>Nome do responsavel:</strong>
  <%= @perfil.nome_do_responsavel %>
</p>

<p>
  <strong>Telefone do responsavel:</strong>
  <%= @perfil.telefone_do_responsavel %>
</p>

<p>
  <strong>Email do responsavel:</strong>
  <%= @perfil.email_do_responsavel %>
</p>

<p>
  <strong>Rua:</strong>
  <%= @perfil.rua %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @perfil.numero %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @perfil.cep %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @perfil.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @perfil.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @perfil.estado %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @perfil.complemento %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @perfil.user_id %>
</p>

<%= link_to 'Edit', edit_perfil_path(@perfil) %> |
<%= link_to 'Back', perfis_path %>